prompt_engineer_task:
  description: >
    Enhance this prompt: "{prompt}"
    Negative prompt: "{negative_prompt} - Do not create infographics."
    For the selected AI model: {selected_model}
    Image Type: {image_type}
    Dimensions: {image_dimensions}
    Image Option: {image_option}

    Your task is to:
    1. Analyze the original prompt and image type requirements.
    2. Structure an enhanced prompt following the model-specific guidelines.
    3. Format the negative prompt according to the selected model's syntax.
    4. Add appropriate technical parameters and settings.
    5. Ensure all text is properly formatted and spelled correctly.

    Image Type-Specific Guidelines:
    - **Realism-Based Images**: Focus on lighting, shadows, and real-world details.
    - **Artistic & Stylized Images**: Specify art style, line work, and color palette.
    - **Abstract & Surreal Images**: Focus on mood, atmosphere, and impossible elements.
    - **Graphics Design**: Centered subjects with dynamic poses or engaging layouts.

    Model-Specific Guidelines:
    - **Ideogram**: Use detailed descriptions and style keywords. Specify the desired style and include technical parameters.
    - **Recraft**: Clearly define the subject and action. Specify the desired style and include details about the scene.
    - **Midjourney**: Use detailed descriptions and style keywords. Include relevant parameters.
    - **Stable Diffusion**: Create longer, detailed prompts. Include negative prompts in a dedicated field.
    - **Leonardo AI**: Create a single, flowing paragraph for the main prompt.
    - **DALL-E**: Keep prompts concise and clear. Include negative elements inline.
    - **Adobe Firefly**: Use creative concepts.

    Image Option Guidelines:
    - **Background Image**: Focus on creating a visually appealing background that complements the main subject. **Do not include any text in the background image.**
      - **Negative Prompt**: "Exclude any text or logos in the background."
    - **Title Image**: Ensure the title image is striking and captures the essence of the content. **Text may be included, but it should be minimal and relevant.**
      - **Negative Prompt**: "Avoid cluttered text or excessive wording."
    - **Thumbnail Image**: Create a thumbnail that is eye-catching and represents the content effectively. **Text should be concise and not overpower the image.**
      - **Negative Prompt**: "Do not use small or hard-to-read text."
    - **Full-Size Image**: Generate a high-resolution image suitable for detailed viewing. **Avoid adding any text unless specified.**
      - **Negative Prompt**: "Exclude any text or annotations."

    Informational & Infographics:
    - Diagrams & Charts: Request clear layout and data visualization
    - Infographics: Specify text accuracy, layout structure, and data flow
    - Always include "with correct spelling and grammar"

    Specific-Use Cases:
    - Logos & Branding: Focus on scalability and brand elements
    - UI/UX Mockups: Include device context and interface elements
    - 3D Renders: Specify lighting, materials, and camera angles
    - AI-Generated Faces: Define demographic details and expressions

    Platform-Specific Image Dimensions & Guidelines:

    Instagram:
      Dimensions:
        - Feed Post: 1080x1080px (1:1 square)
        - Stories/Reels: 1080x1920px (9:16)
        - Carousel: 1080x1080px (1:1)
        - IGTV Cover: 420x654px (1:1.55)
      Style Guidelines:
        - High-quality, visually striking images
        - Clear focal point
        - Brand consistent colors
        - Space for text overlay (if needed)
        - Mobile-first optimization

    Facebook:
      Dimensions:
        - Feed Post: 1200x630px (1.91:1)
        - Stories: 1080x1920px (9:16)
        - Profile Picture: 170x170px
        - Cover Photo: 851x315px
      Style Guidelines:
        - Engaging visuals that stop scrolling
        - Clear branding elements
        - Text overlay friendly
        - Attention to mobile and desktop views

    LinkedIn:
      Dimensions:
        - Feed Post: 1200x627px (1.91:1)
        - Company Banner: 1536x768px
        - Profile Banner: 1584x396px
        - Profile Picture: 400x400px
      Style Guidelines:
        - Professional and clean aesthetic
        - Corporate-friendly imagery
        - Clear value proposition space
        - Brand consistency

    Twitter:
      Dimensions:
        - Feed Post: 1600x900px (16:9)
        - Header Photo: 1500x500px
        - Profile Picture: 400x400px
      Style Guidelines:
        - Eye-catching visuals
        - Clear messaging
        - Mobile-optimized
        - Space for tweet text

    YouTube:
      Dimensions:
        - Thumbnail: 1280x720px (16:9)
        - Channel Banner: 2560x1440px
        - Channel Profile: 800x800px
      Style Guidelines:
        - High contrast for visibility
        - Clear, readable text
        - Emotional hooks
        - Action-oriented visuals
        - Avoid cluttered backgrounds

    Pinterest:
      Dimensions:
        - Standard Pin: 1000x1500px (2:3)
        - Square Pin: 1000x1000px
        - Story Pin: 1080x1920px
      Style Guidelines:
        - Vertical orientation preferred
        - Rich, detailed visuals
        - Clear typography
        - Inspirational content
        - Brand watermarks

    Content Type Guidelines:

    Marketing Materials:
      - Product Photos: Clean background, detailed features
      - Brand Assets: Consistent style, scalable elements
      - Promotional Graphics: Clear CTA, compelling visuals
      - Campaign Images: Theme consistency, emotional appeal

    Social Content:
      - UGC Style: Authentic, relatable imagery
      - Story Content: Dynamic, engaging visuals
      - Educational Posts: Clear information hierarchy
      - Entertainment: Eye-catching, shareable content

    Important Technical Notes:
      - Always maintain aspect ratio when resizing
      - Consider safe zones for text and important elements
      - Export in appropriate format (JPG for photos, PNG for graphics)
      - Optimize file size without quality loss
      - Test visibility on both dark and light modes

    Important:
    - Maintain the core elements of the original prompt
    - Don't add artistic mediums unless specified in the original prompt
    - Preserve the user's creative intent
    - Reason again and again until you are confident that you are giving correct answer
    - Think as a human being that are you giving what the user asked for? if not then try again and again till you are confident that results are what user asked for
    - For infographics, double-check that the prompt emphasizes text accuracy and clarity

    # New section for social media post guidelines
    Social Media Post Guidelines:
    - **Fundamentals of Graphic Design**:
      - **Contrast**: Create visual interest and hierarchy.
      - **Alignment**: Ensure elements line up for a clean look.
      - **Hierarchy**: Prioritize important elements.
      - **Proximity**: Group related elements for readability.
      - **Balance**: Distribute elements for stability.
      - **Repetition/Consistency**: Create unity and brand recognition.

    - **Branding Essentials**:
      - **Brand Core**: Define mission, vision, and values.
      - **Brand Personality**: Reflect human traits in design.
      - **Visual Brand Guidelines**: Clear rules on logo, color, typography, and imagery.

    - **Creating Effective Social Media Posts**:
      - **Know Your Audience**: Understand demographics and preferences.
      - **Define the Goal**: Clarify the post's objective.
      - **Design Best Practices**: Clear focal point, concise text, strong CTA, and optimized layout.
      - **Typography & Readability**: Use legible fonts and high contrast.
      - **Color Usage**: Use on-brand colors and avoid over-saturation.
      - **Imagery & Iconography**: Use high-quality visuals and relevant icons.

    - **Best Practices for Advertisement Posts**:
      - **Immediate Impact**: Use bold visuals or headlines.
      - **Simplicity & Clarity**: Avoid clutter.
      - **Compelling CTA**: Ensure the CTA stands out.
      - **Alignment with Brand Identity**: Consistent use of brand elements.
      - **Use of Negative Space**: Guide the eye to important content.
      - **Test & Refine**: Run A/B tests for better engagement.
      - **Accessibility**: Consider color-blind safe palettes and text size.

    # New section for advertisement image type
    Advertisement Image Type:
    - **Advertisement Images**: High-quality visuals that effectively showcase the product or service. These images should:
      - Highlight the product in a clean and appealing manner.
      - Depict the product in use or in a lifestyle context to help consumers visualize its application.
      - Include promotional elements such as discounts or calls to action (CTAs).
      - Maintain brand consistency through the use of logos, colors, and typography.
      - Utilize high-quality imagery to enhance credibility and engagement.
      - Be adaptable for various platforms, ensuring optimal dimensions and layouts.
      - **Backgrounds**: Use solid or abstract backgrounds that complement the image graphics, avoiding busy or distracting backgrounds.

    # Advertisement Image Guidelines
    Advertisement Image Guidelines:
    - **Understand Platform-Specific Requirements**: Different social media platforms have specific requirements for ad sizes, aspect ratios, and text-to-image ratios.
    - **Maintain Consistent Visual Identity**: Ensure that your ad design is consistent with your brand's visual identity, including color palette, typography, and imagery.
    - **Use Clear and Compelling Messaging**: Craft short, concise, and attention-grabbing ad copy that quickly conveys the value proposition.
    - **Utilize High-Quality Images and Graphics**: Use high-quality images and graphics relevant to your ad's message.
    - **Incorporate Video for Higher Engagement**: Incorporate video content into your social media ads to significantly increase engagement rates.
    - **Experiment with Different Formats**: Experiment with different formats such as videos, carousels, and interactive elements.
    - **Stay Updated with Design Trends**: Stay updated with the latest design trends to ensure your visuals feel modern and relevant.
    - **Test Different Visual Strategies**: Use A/B testing to determine which designs and messages are most effective.
    - **Be Detailed in Your Prompts**: Be as detailed as possible in your prompts for AI tools.
    - **Customize and Iterate**: Customize generated templates or images further to align with your brand identity.
    - **Do Not Create Infographics**: When the advertisement type is selected, do not create infographics. Focus solely on advertisement guidelines.

    Blog Thumbnail:
      - **Focus**: Create a visually striking image that encapsulates the essence of the blog post.
      - **Text Overlay**: Include the blog title or a catchy phrase, ensuring it is legible and stands out against the background.
      - **Color Scheme**: Use colors that align with the blog's branding while ensuring high contrast for readability.
      - **Imagery**: Incorporate relevant visuals that represent the content of the blog, such as illustrations, photographs, or graphics.
      - **Aspect Ratio**: Typically use a 16:9 ratio for optimal display on most platforms.
      - **Call to Action**: If applicable, include a subtle call to action to encourage clicks.
      - **Branding**: Ensure the blog's logo or branding elements are subtly integrated into the design.

  expected_output: |
    A refined and optimized prompt including specific artistic direction, technical details, and correct formatting based on the selected AI model.
    Negative Prompt: A properly formatted negative prompt with clear exclusions, ensuring optimal image generation.
    Additional quality settings, aspect ratio, and other necessary technical details tailored for the selected model.
  agent: prompt_engineer

# image_generator_task:
#   description: >
#     Generate an image based on the prompt.
#   expected_output: >
#     A fully fledged image.
#   agent: image_generator
#   max_iterations: 1

